CREATE TABLE users (
  id BIGINT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  preferred_name VARCHAR(10) NOT NULL,
  picture VARCHAR(256),
  email VARCHAR(50) NOT NULL,
  password VARCHAR(36) NOT NULL,
  salt CHAR(8) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);